version: '3.8'

services:
  # Playwright tests - isolated container with copied files
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    volumes:
      # Only mount output directories that host needs access to
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - CI=true
      - RECORD_VIDEO=${RECORD_VIDEO:-false}
      - OPENCODE_URL=http://127.0.0.1:4096
    network_mode: host # Access host's OpenCode on port 4096
    command: pnpm test:e2e
    stdin_open: true
    tty: true
