version: '3.8'

services:
  # Playwright tests only - uses OpenCode from host
  playwright:
    image: mcr.microsoft.com/playwright:v1.55.0-noble
    working_dir: /app
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - CI=true
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    network_mode: host # Access host's OpenCode on port 4096
    command: sh -c "npm install -g pnpm@10.14.0 && pnpm install --frozen-lockfile && pnpm test:e2e"
    stdin_open: true
    tty: true
