name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10.14.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

    - name: Install OpenCode CLI
      run: |
        curl -fsSL https://github.com/sst/opencode/releases/latest/download/opencode-linux-x64.tar.gz | tar -xz
        sudo mv opencode /usr/local/bin/
        opencode --version
    
    - name: Start OpenCode for testing
      run: |
        mkdir -p .test-opencode
        cd .test-opencode
        echo '{"models":{"default":"claude-3-5-sonnet-20241022"}}' > claude_config.json
        opencode serve --port 4096 --hostname 127.0.0.1 &
        sleep 5

      - name: Run Playwright tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
